<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Customer;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        $customerData = [
            [
                'first_name' => 'يوسف',
                'last_name' => 'البعداني',
                'email' => 'yousef.badani@example.com',
                'username' => 'yousef_badani',
                'phone' => '967771234567',
                'address' => 'شارع الستين، حي السبعين',
                'city' => 'صنعاء',
                'postal_code' => '11001',
            ],
            [
                'first_name' => 'أروى',
                'last_name' => 'الزبيدي',
                'email' => 'arwa.zubaidi@example.com',
                'username' => 'arwa_zubaidi',
                'phone' => '967772345678',
                'address' => 'شارع التحرير، حي كريتر',
                'city' => 'عدن',
                'postal_code' => '12002',
            ],
            [
                'first_name' => 'معاذ',
                'last_name' => 'الآنسي',
                'email' => 'muath.ansi@example.com',
                'username' => 'muath_ansi',
                'phone' => '967773456789',
                'address' => 'شارع جمال، حي القاهرة',
                'city' => 'تعز',
                'postal_code' => '13003',
            ],
            [
                'first_name' => 'سميرة',
                'last_name' => 'المخلافي',
                'email' => 'samira.mikhlafi@example.com',
                'username' => 'samira_mikhlafi',
                'phone' => '967774567890',
                'address' => 'شارع صنعاء، حي الحالي',
                'city' => 'الحديدة',
                'postal_code' => '14004',
            ],
            [
                'first_name' => 'نبيل',
                'last_name' => 'الحبيشي',
                'email' => 'nabil.habishi@example.com',
                'username' => 'nabil_habishi',
                'phone' => '967775678901',
                'address' => 'شارع السلام، حي المظفر',
                'city' => 'إب',
                'postal_code' => '15005',
            ],
            [
                'first_name' => 'أمل',
                'last_name' => 'الذبحاني',
                'email' => 'amal.thabhani@example.com',
                'username' => 'amal_thabhani',
                'phone' => '967776789012',
                'address' => 'شارع الخمسين، حي المعبر',
                'city' => 'ذمار',
                'postal_code' => '16006',
            ],
            [
                'first_name' => 'جمال',
                'last_name' => 'السقاف',
                'email' => 'jamal.saqqaf@example.com',
                'username' => 'jamal_saqqaf',
                'phone' => '967777890123',
                'address' => 'شارع الميناء، حي الشيخ عثمان',
                'city' => 'عدن',
                'postal_code' => '17007',
            ],
            [
                'first_name' => 'رؤى',
                'last_name' => 'الشميري',
                'email' => 'ruaa.shamiri@example.com',
                'username' => 'ruaa_shamiri',
                'phone' => '967778901234',
                'address' => 'شارع الزبيري، حي شعوب',
                'city' => 'صنعاء',
                'postal_code' => '18008',
            ],
            [
                'first_name' => 'طارق',
                'last_name' => 'العديني',
                'email' => 'tariq.adini@example.com',
                'username' => 'tariq_adini',
                'phone' => '967779012345',
                'address' => 'شارع الأربعين، حي صالة',
                'city' => 'تعز',
                'postal_code' => '19009',
            ],
            [
                'first_name' => 'هناء',
                'last_name' => 'الوصابي',
                'email' => 'hana.wasabi@example.com',
                'username' => 'hana_wasabi',
                'phone' => '967770123456',
                'address' => 'شارع صبر، حي الروضة',
                'city' => 'مأرب',
                'postal_code' => '20010',
            ],
            [
                'first_name' => 'أحمد',
                'last_name' => 'الدبعي',
                'email' => 'ahmed.dabie@example.com',
                'username' => 'ahmed_dabie',
                'phone' => '967771111222',
                'address' => 'شارع الحديدة، حي الجامعة',
                'city' => 'إب',
                'postal_code' => '21011',
            ],
            [
                'first_name' => 'منى',
                'last_name' => 'القاسمي',
                'email' => 'mona.qasemi@example.com',
                'username' => 'mona_qasemi',
                'phone' => '967772222333',
                'address' => 'شارع تعز، حي النهضة',
                'city' => 'صنعاء',
                'postal_code' => '22012',
            ],
            [
                'first_name' => 'خالد',
                'last_name' => 'اليمني',
                'email' => 'khaled.yemeni@example.com',
                'username' => 'khaled_yemeni',
                'phone' => '967773333444',
                'address' => 'شارع المطار، حي الصافية',
                'city' => 'عدن',
                'postal_code' => '23013',
            ],
            [
                'first_name' => 'ندى',
                'last_name' => 'الخولاني',
                'email' => 'nada.kholani@example.com',
                'username' => 'nada_kholani',
                'phone' => '967774444555',
                'address' => 'شارع الحصبة، حي شميلة',
                'city' => 'صنعاء',
                'postal_code' => '24014',
            ],
            [
                'first_name' => 'عمر',
                'last_name' => 'الكبسي',
                'email' => 'omar.kabsi@example.com',
                'username' => 'omar_kabsi',
                'phone' => '967775555666',
                'address' => 'شارع بير باشا، حي المطار',
                'city' => 'تعز',
                'postal_code' => '25015',
            ],
            [
                'first_name' => 'إيمان',
                'last_name' => 'الغفاري',
                'email' => 'eman.ghafari@example.com',
                'username' => 'eman_ghafari',
                'phone' => '967776666777',
                'address' => 'شارع الزراعة، حي التحرير',
                'city' => 'إب',
                'postal_code' => '26016',
            ],
            [
                'first_name' => 'سعيد',
                'last_name' => 'القاضي',
                'email' => 'saeed.qadi@example.com',
                'username' => 'saeed_qadi',
                'phone' => '967777777888',
                'address' => 'شارع الشهداء، حي الدائري',
                'city' => 'عدن',
                'postal_code' => '27017',
            ],
            [
                'first_name' => 'ليلى',
                'last_name' => 'البكري',
                'email' => 'layla.bakri@example.com',
                'username' => 'layla_bakri',
                'phone' => '967778888999',
                'address' => 'شارع 26 سبتمبر، حي الحوبان',
                'city' => 'تعز',
                'postal_code' => '28018',
            ],
            [
                'first_name' => 'مازن',
                'last_name' => 'الحميدي',
                'email' => 'mazen.humaidi@example.com',
                'username' => 'mazen_humaidi',
                'phone' => '967779999000',
                'address' => 'شارع حدة، حي بيت بوس',
                'city' => 'صنعاء',
                'postal_code' => '29019',
            ],
            [
                'first_name' => 'سامر',
                'last_name' => 'الشيباني',
                'email' => 'samer.shaibani@example.com',
                'username' => 'samer_shaibani',
                'phone' => '967770000111',
                'address' => 'شارع التحرير، حي الحديدة',
                'city' => 'الحديدة',
                'postal_code' => '30020',
            ],
            [
                'first_name' => 'فاطمة',
                'last_name' => 'العلوي',
                'email' => 'fatima.alawi@example.com',
                'username' => 'fatima_alawi',
                'phone' => '967771111222',
                'address' => 'شارع الستين، حي الجامعة',
                'city' => 'صنعاء',
                'postal_code' => '31021',
            ],
            [
                'first_name' => 'محمد',
                'last_name' => 'النقيب',
                'email' => 'mohammed.naqeeb@example.com',
                'username' => 'mohammed_naqeeb',
                'phone' => '967772222333',
                'address' => 'شارع القيادة، حي التحرير',
                'city' => 'عدن',
                'postal_code' => '32022',
            ],
            [
                'first_name' => 'عبدالله',
                'last_name' => 'الحسني',
                'email' => 'abdullah.hassani@example.com',
                'username' => 'abdullah_hassani',
                'phone' => '967773333444',
                'address' => 'شارع الزبيري، حي الروضة',
                'city' => 'تعز',
                'postal_code' => '33023',
            ],
            [
                'first_name' => 'ريم',
                'last_name' => 'الشعبي',
                'email' => 'reem.shaabi@example.com',
                'username' => 'reem_shaabi',
                'phone' => '967774444555',
                'address' => 'شارع الخمسين، حي الجامعة',
                'city' => 'إب',
                'postal_code' => '34024',
            ],
            [
                'first_name' => 'أسامة',
                'last_name' => 'الجنيد',
                'email' => 'osama.junaid@example.com',
                'username' => 'osama_junaid',
                'phone' => '967775555666',
                'address' => 'شارع الثورة، حي الحوض',
                'city' => 'عدن',
                'postal_code' => '35025',
            ],
            [
                'first_name' => 'سارة',
                'last_name' => 'العنسي',
                'email' => 'sara.ansi@example.com',
                'username' => 'sara_ansi',
                'phone' => '967776666777',
                'address' => 'شارع جمال، حي القبة',
                'city' => 'صنعاء',
                'postal_code' => '36026',
            ],
            [
                'first_name' => 'زياد',
                'last_name' => 'البحري',
                'email' => 'ziad.bahri@example.com',
                'username' => 'ziad_bahri',
                'phone' => '967777777888',
                'address' => 'شارع 14 أكتوبر، حي المعلا',
                'city' => 'عدن',
                'postal_code' => '37027',
            ],
            [
                'first_name' => 'رنا',
                'last_name' => 'الشامي',
                'email' => 'rana.shami@example.com',
                'username' => 'rana_shami',
                'phone' => '967778888999',
                'address' => 'شارع الميناء، حي الجامعة',
                'city' => 'الحديدة',
                'postal_code' => '38028',
            ],
            [
                'first_name' => 'باسم',
                'last_name' => 'الأنصاري',
                'email' => 'basem.ansari@example.com',
                'username' => 'basem_ansari',
                'phone' => '967779999000',
                'address' => 'شارع صعدة، حي الحصبة',
                'city' => 'صنعاء',
                'postal_code' => '39029',
            ],
            [
                'first_name' => 'هدى',
                'last_name' => 'البخيتي',
                'email' => 'huda.bakheti@example.com',
                'username' => 'huda_bakheti',
                'phone' => '967770000111',
                'address' => 'شارع الأربعين، حي المعافر',
                'city' => 'تعز',
                'postal_code' => '40030',
            ],
        ];
        
        foreach ($customerData as $data) {
            $user = User::create([
                'first_name' => $data['first_name'],
                'last_name' => $data['last_name'],
                'email' => $data['email'],
                'username' => $data['username'],
                'phone' => $data['phone'],
                'password' => Hash::make('password123'),
                'status' => 'active',
            ]);

            Customer::create([
                'user_id' => $user->id,
                'address' => $data['address'],
                'city' => $data['city'],
                'postal_code' => $data['postal_code'],
            ]);
        }
    }
}
