<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('product_images')->insert([
            [
                'product_id' => 1,
                'product_variant_id' => null,
                'image' => '1.jpg',
                'alt_text' => 'Example Image 1',
                'is_primary' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'product_variant_id' => null,
                'image' => '2.webp',
                'alt_text' => 'Image 2',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'product_variant_id' => null,
                'image' => '3.webp',
                'alt_text' => 'Image 3',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'product_variant_id' => null,
                'image' => '4.webp',
                'alt_text' => 'Image 4',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'product_variant_id' => null,
                'image' => '5.webp',
                'alt_text' => 'Image 3',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'product_variant_id' => null,
                'image' => 'iphone1.jpg',
                'alt_text' => 'iphone 1',
                'is_primary' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'product_variant_id' => null,
                'image' => 'iphone2.webp',
                'alt_text' => 'iphone 2',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'product_variant_id' => null,
                'image' => 'iphone3.jpg',
                'alt_text' => 'iphone 3',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'product_variant_id' => null,
                'image' => 'iphone4.webp',
                'alt_text' => 'iphone 4',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'product_variant_id' => null,
                'image' => 'iphone5.webp',
                'alt_text' => 'iphone 5',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'product_variant_id' => null,
                'image' => 'men1.webp',
                'alt_text' => 'men 1',
                'is_primary' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'product_variant_id' => null,
                'image' => 'men2.webp',
                'alt_text' => 'men 2',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'product_variant_id' => null,
                'image' => 'men3.jpg',
                'alt_text' => 'men 3',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'product_variant_id' => null,
                'image' => 'men4.jpg',
                'alt_text' => 'men 4',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'product_variant_id' => null,
                'image' => 'men5.jpg',
                'alt_text' => 'men 5',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'product_variant_id' => null,
                'image' => 'wemen1.jpg',
                'alt_text' => 'wemen 1',
                'is_primary' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'product_variant_id' => null,
                'image' => 'wemen2.webp',
                'alt_text' => 'wemen 2',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'product_variant_id' => null,
                'image' => 'wemen3.html',
                'alt_text' => 'wemen 3',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'product_variant_id' => null,
                'image' => 'wemen4.jpg',
                'alt_text' => 'wemen 4',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'product_variant_id' => null,
                'image' => 'wemen5.jpg',
                'alt_text' => 'wemen 5',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 5,
                'product_variant_id' => null,
                'image' => 'home1.jpg',
                'alt_text' => 'home 1',
                'is_primary' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 5,
                'product_variant_id' => null,
                'image' => 'home2.webp',
                'alt_text' => 'home 2',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 5,
                'product_variant_id' => null,
                'image' => 'home3.jpg',
                'alt_text' => 'home 3',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 5,
                'product_variant_id' => null,
                'image' => 'home4.webp',
                'alt_text' => 'home 4',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 5,
                'product_variant_id' => null,
                'image' => 'home5.jpg',
                'alt_text' => 'home 5',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'product_variant_id' => null,
                'image' => 'perfume1.webp',
                'alt_text' => 'perfume 1',
                'is_primary' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'product_variant_id' => null,
                'image' => 'perfume2.webp',
                'alt_text' => 'perfume 2',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'product_variant_id' => null,
                'image' => 'perfume3.webp',
                'alt_text' => 'perfume 3',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'product_variant_id' => null,
                'image' => 'perfume4.webp',
                'alt_text' => 'perfume 4',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'product_variant_id' => null,
                'image' => 'perfume5.webp',
                'alt_text' => 'perfume 5',
                'is_primary' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}